### ISSUE TITLE
FarSync TE1e

### ISSUE THREAD

**Issue by janblaesi** [Opendigitalradio/ODR-DabMux#34]
Hi there,
it's me again!
This will probably not classify as an issue, but probably you can help me:
We are trying to get an Farsite FarSync TE1e PCI card working on our Buildroot system with odr-zmq2farsync, we have the farsync and hdlc kernel modules loaded, "hdlc0" is showing up in network devices but passing that name to odr-zmq2farsync shows "Cyclades card identified" and then "hdlc0: Wrong parameter" or something similar. Are we doing something wrong in calling the binary? Or is another driver for the card needed?
Greetings,
Jan

**Comment by mpbraendli** [comment]
@stanroehrich do you have some advice for this question?

**Comment by stanroehrich** [comment]
I Didn't installed since a while a TE1e but the you should be able to call sync0 to pass the card parameter.   This using Farutil. The first thing to check is on this link before going further:   https://www.farsite.com/custsupp/tsg/Linux_X21/TSG_FarSync_X21_T-Series_farutil_Linux.htm

You should then normally see on the interface list your eth0,1,...  lo, and a sync0 interface

This old link give additional information too on the principle (but was old driver)  https://wiki.opendigitalradio.org/Farsync_card

As a exemple the call on the mux should use raw output and the interface name (with an external 10Mhz clock feed to the farsync) 
raw://sync0?clocking=master&extsyncclock=10000000 

Don't forget before to use the card with the mux to select the BNC connector (by moving the jumper on the card and to select BNC with farutil argument. 

that's the setup you should have with the card then:

firmware id:	5	firmware vers:	1.00.02
Card Rev:	0.3A

Configuration for port 0 
physical:	E1 
  active alarms:	LOS 
  clock mode:		Master
  datarate:		2048000
  start slot:		0
  structure:		Unframed
  interface:		BNC
  coding:		HDB3
  equalizer:		Short Haul
  loop mode:		None
  tx buff mode:		2 frame
  rx buff mode:		2 frame
  idle code:		0xFF
  ext sync clk:		Enabled
  clk d.c. offset:	False
  ext sync clk rate:	10000000
  1PPS sync:		Disabled
  1PPS clk d.c. offset:	False
Stats:
  Receive Buffer Delay:	33
  Framing Error Count:	0
  Code Violation Count:	0
  CRC Error Count:	0
  Line Attenuation:	Unknown
protocol:	Raw packet interface
line mode:	Transparent
Buffer configuration:
  no of rx buffers:	8	size of rx buffers:	6144
  no of tx buffers:	8	size of tx buffers:	6144

**Comment by mpbraendli** [comment]
No updates, please open the issue again if your issue is still unsolved.

**Comment by mspanc** [comment]
What version of ODB-DabMux supports passing extra parameters to the farsync output? I tried to add this and I have the following error

```
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]: Welcome to ODR-DabMux 1.2.1, compiled at Mar  5 2017, 19:36:21
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]: Copyright (C) 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]: Her Majesty the Queen in Right of Canada
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]: (Communications Research Centre Canada) All rights reserved.
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]: Copyright (C) 2016 Matthias P. Braendli
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]: http://opendigitalradio.org
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]: Input URLs supported:
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]:  prbs udp file zmq
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]: Inputs format supported:
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]:  raw mpeg packet epm
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]: Output URLs supported:
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]:  file fifo udp tcp raw simul
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]:       ODR-DabMux 1.2.1 starting up
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]:       RC: Waiting for connection on port 5001
Jan 09 11:53:57 dab-int1-001 ODR-DabMux[5701]: ODR-DabMux ODR-DabMux 1.2.1 starting up
Jan 09 11:53:57 dab-int1-001 ODR-DabMux[5701]: ODR-DabMux RC: Waiting for connection on port 5001
Jan 09 11:53:57 dab-int1-001 ODR-DabMux[5701]: ODR-DabMux Cyclades card identified.
Jan 09 11:53:57 dab-int1-001 odr-dabmux[5701]:       Cyclades card identified.
Jan 09 11:53:57 dab-int1-001 ODR-DabMux[5701]: ODR-DabMux Can't get raw device MTU!
Jan 09 11:53:57 dab-int1-001 ODR-DabMux[5701]: ODR-DabMux Unable to open output raw://sync0?clocking=master&extsyncclock=10000000
```

**Comment by mpbraendli** [comment]
Ooof I don't know by heart! Have a look at the ChangeLog and the git log of `src/dabOutput/dabOutputRaw.cpp` and maybe the config file parser `src/ConfigParser.cpp`. Tell me if you get stuck in your search and I'll try to assist.
