### ISSUE TITLE
ERROR Total size in CU exceeds 864 when use Dabmux to generate eti

### ISSUE THREAD

**Issue by yansoly** [Opendigitalradio/ODR-DabMux#76]
Dear dabmux group,

when I try to genterate eti files by odr-Dabmux, I succeeded to get it, but when I added service number above 8, it reported Error, 
![dabmux-error](https://github.com/user-attachments/assets/9b544ade-858a-431c-9e0f-ddd6ef408501)
As showing attached picture.
is there any expert to explain and solve this issue for me?

**Comment by andimik** [comment]
https://opendigitalradio.github.io/cu_calc/

This page will help you to calculate it.

Your screenshot shows 128 kBit mp2 in Protection Level UEP 1, which are 140 CUs. Assuming the others have the same size, you cannot add six services as you will exceed the maximum capacity.

Try to reduce the protection level or the bitrate or use AAC instead of mp2.

**Comment by mpbraendli** [comment]
Since this is not an issue in odr-dabmux, I'm closing this. But please feel free to continue the discussion here!
